### ISSUE TITLE
About the EdNet datasets

### ISSUE THREAD

**Issue by hfimmortal** [Yumo216/DGEKT#1]
Could you please specify which dataset,  EdNet -KT1, EdNet -KT2, EdNet -KT3, or EdNet -KT4, is utilized in this article on the EdNet dataset?

**Comment by Yumo216** [comment]
Hi, thanks for your question.We used EdNet -KT1 as the EdNet dataset.

**Comment by hfimmortal** [comment]
Thank you very much for your reply.
