### ISSUE TITLE
 Model Visualization

### ISSUE THREAD

**Issue by Yingying933** [Yumo216/DGEKT#3]
Hello,In order to better understand the ability of DGEKT to represent students’ learning interactions, we visualize the
embeddings of learning interactions generated from CAHG and DTG
Could you please share the code?

**Comment by Yumo216** [comment]
Hello, the code for the visualization work can no longer be found. However, CAHG used the t-SNE method, and DTG used the method of clustering the embeddings of questions into ten categories and then assigning different colors. Wish you success in your experiments!
