### ISSUE TITLE
2017.csv

### ISSUE THREAD

**Issue by jia-qiang** [Yumo216/DGEKT#4]
你好，能分享下论文代码里的 /Dataset/H/2017.csv 的生成代码吗？

**Comment by Yumo216** [comment]
这是我很之前的工作，已经找不到代码了。不过这个很好实现，根据数据集中题目和知识概念的关系，生成超图的关联矩阵就行。

**Comment by jia-qiang** [comment]
谢了

**Comment by anorigin** [comment]
你好，我想问一下2017.csv中的行和列是按照题目id和知识概念id的顺序排列的吗？非常感谢！

**Comment by anorigin** [comment]
你好，我在尝试根据assit2017生成2017.csv文件时，有一个地方不是很明白，在您提供的2017.csv中为什么会出现（v1-，H1+）=1以及（v1-，H1-）=0；我感觉这种关系在逻辑上是不一致的，感觉如果学生掌握了知识点（H1+），不应该会出现（v1-）吧。根据您论文中的3.2.1 Concept Association Hypergraph，应该是vi+ ∈ Hj+ 或 vi− ∈ Hj−时Hi,j的值才会是1吧。  也有可能是我目前还没理解好您论文中超图的定义，谢谢！
​

**Comment by jia-qiang** [comment]
你找错人了，我不是作者



在 2024-12-31 13:09:52，"anorigin" ***@***.***> 写道：

你好，我在尝试根据assit2017生成2017.csv文件时，有一个地方不是很明白，在您提供的2017.csv中为什么会出现（v1-，H1+）=1以及（v1-，H1-）=0；我感觉这种关系在逻辑上是不一致的，感觉如果学生掌握了知识点（H1+），不应该会出现（v1-）吧。根据您论文中的3.2.1 Concept Association Hypergraph，应该是vi+ ∈ Hj+ 或 vi− ∈ Hj−时Hi,j的值才会是1吧。 也有可能是我目前还没理解好您论文中超图的定义，谢谢！
​

**Comment by anorigin** [comment]
好滴，不好意思哈



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 4, 2025 14:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Yumo216/DGEKT] 2017.csv (Issue #4)




 你找错人了，我不是作者
 
 
 
 在 2024-12-31 13:09:52，"anorigin" ***@***.***&gt; 写道：
 
 你好，我在尝试根据assit2017生成2017.csv文件时，有一个地方不是很明白，在您提供的2017.csv中为什么会出现（v1-，H1+）=1以及（v1-，H1-）=0；我感觉这种关系在逻辑上是不一致的，感觉如果学生掌握了知识点（H1+），不应该会出现（v1-）吧。根据您论文中的3.2.1 Concept Association Hypergraph，应该是vi+ ∈ Hj+ 或 vi− ∈ Hj−时Hi,j的值才会是1吧。 也有可能是我目前还没理解好您论文中超图的定义，谢谢！
 ​

**Comment by YukinaMano** [comment]
> 你好，我在尝试根据assit2017生成2017.csv文件时，有一个地方不是很明白，在您提供的2017.csv中为什么会出现（v1-，H1+）=1以及（v1-，H1-）=0；我感觉这种关系在逻辑上是不一致的，感觉如果学生掌握了知识点（H1+），不应该会出现（v1-）吧。根据您论文中的3.2.1 Concept Association Hypergraph，应该是vi+ ∈ Hj+ 或 vi− ∈ Hj−时Hi,j的值才会是1吧。 也有可能是我目前还没理解好您论文中超图的定义，谢谢！​

我仔细研究了H文件，实际上是不存在v+属于H-超边和v-属于H+超边这两种情况的，也就是说右上和左下的分块矩阵实际是零矩阵。原因也很简单，生成超边时是通过遍历序列中的时间步完成的，而对于同一个时间步是不可能同时存在(q, +)和(s, -)的，另外一种情况也是同理。

**Comment by YukinaMano** [comment]
> > 你好，我在尝试根据assit2017生成2017.csv文件时，有一个地方不是很明白，在您提供的2017.csv中为什么会出现（v1-，H1+）=1以及（v1-，H1-）=0；我感觉这种关系在逻辑上是不一致的，感觉如果学生掌握了知识点（H1+），不应该会出现（v1-）吧。根据您论文中的3.2.1 Concept Association Hypergraph，应该是vi+ ∈ Hj+ 或 vi− ∈ Hj−时Hi,j的值才会是1吧。 也有可能是我目前还没理解好您论文中超图的定义，谢谢！​
> 
> 我仔细研究了H文件，实际上是不存在v+属于H-超边和v-属于H+超边这两种情况的，也就是说右上和左下的分块矩阵实际是零矩阵。原因也很简单，生成超边时是通过遍历序列中的时间步完成的，而对于同一个时间步是不可能同时存在(q, +)和(s, -)的，另外一种情况也是同理。

一个更容易推理的情况是：因为数据集都做得很好，样本量很大，导致了：几乎对所有题目，有回答对的就有回答错的记录。也就是说：实际上左上和右下的矩阵是完全一致的。
